### PR TITLE
Homestead contract creation gas cost

### PR DESCRIPTION
**Pull request by mratsim**
See EIP-2: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md
and https://etherscan.io/tx/0x31ded263506ea36e6ea777efc2c39a999e6fba4f4d338c7313af6aac6d9bf3e3

Contract creation was 21k + 0 instead of the current 21k + 32k.

### CODE REVIEW

**Comment by yglukhov** [comment]
Appveyor failed. Is that ok?

**Comment by mratsim** [comment]
It failed for 32-bit only, 64-bit worked. And it was out of bounds memory access.

I don't think it's related but I'm surprised that didn't come up earlier.

**Comment by coffeepots** [comment]
I was just looking at that, the out of bounds error doesn't seem to happen on master for test_vm_json.

**Comment by coffeepots** [comment]
LGTM. The out of bounds error means the index `<0` or `>Int32`. Unlikely to be anything to do with this PR.

**Pull request merged**
