### PR TITLE
Fix block 78458 crash

### PR DESCRIPTION
**Pull request by jangko**
summary of this PR:
* allow us to sync until block 81383
* pass additional 122 GST

### CODE REVIEW

**Comment by zah** [comment]
Will merge once the CI is green.

**Comment by jangko** [comment]
> Let's make the snapshot API and usages a bit more exception-safe.

agree, it should be our next priority.

**Comment by jangko** [comment]
why the Appveyor often failed with this kind of error now?

> Error downloading remote file: One or more errors occurred. Inner Exception: Unable to connect to the remote server. Command exited with code 2

**Comment by cheatfate** [comment]
Mostly because `sourceforge.net` from where we trying to download `mingw` distro are not available 100% of time.

**Comment by stefantalpalaru** [comment]
> Mostly because `sourceforge.net` from where we trying to download `mingw` distro are not available 100% of time.

Did you know that multiple Mingw-w64 versions are already available in AppVeyor images? That's what I ended up using after running into the same problem: https://github.com/status-im/nimbus/blob/5ade849e176725f2e1fa16a35e91b56bbe3fc1bd/.appveyor.yml

**Pull request merged**
