### PR TITLE
[WIP] implement EIP158/EIP161 a.k.a Spurious Dragon fork

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

**Comment by jangko** [comment]
this PR is ready. review please

**Comment by stefantalpalaru** [comment]
Why is Travis failing?

**Comment by jangko** [comment]
don't know, it's green on [my repo](https://github.com/jangko/nimbus/pull/7)

**Comment by stefantalpalaru** [comment]
Looks like I'm the one who broke Travis. It's fixed now: https://travis-ci.org/status-im/nimbus/builds/522108146

**Pull request merged**
