### PR TITLE
Nim1.0.6

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by zah** [comment]
Something looks wrong here. Why was `newBlockchainsTest.md` changed?

**Comment by stefantalpalaru** [comment]
> Why was newBlockchainsTest.md changed?

Because I run the tests locally and the local test log gets updated. Guess why it wasn't updated when the tests changed.

**Comment by zah** [comment]
I don't follow. The set of executed tests changes for some reason and it's not clear why. @jangko must comment whether this is expected, but he'll probably need some input from you regarding how you executed the tests.

**Comment by stefantalpalaru** [comment]
> The set of executed tests changed for some reason and it's not clear why.

https://github.com/status-im/nimbus/commits/master/tests

> how you executed the tests

Same as the CI setup does: `make test`.

The problem here is that the policy of running the tests locally and committing their changed logs every time the tests are changed is not respected.

**Comment by jangko** [comment]
my local `newBlockchainsTest.md ` shows:
```text
---TOTAL---
OK: 2621/2730 Fail: 0/2730 Skip: 109/2730
```

while your commit shows:
```
---TOTAL---
OK: 0/0 Fail: 0/0 Skip: 0/0
```

and my Nim compiler version:
```text
Nim Compiler Version 1.0.6 [Windows: amd64]
Compiled at 2020-01-28
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 89b39ee8fe271d0e1b75c15a4c6cf82eb9c13aea
active boot switches: -d:release
```

I could not reproduce the behavior above, clearly something amiss(probably on linux/posix).

I also could not reproduce the Appveyor failure, still have no idea why. OOM should not be a problem anymore.

```text
[00:42:51] [Suite] stack
[00:42:51] SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by stefantalpalaru** [comment]
None of the "new block chain json tests" run on Linux: https://travis-ci.org/status-im/nimbus/jobs/642432821#L15382

**Comment by jangko** [comment]
When we switch to v1.0.0, 1.0.2, and 1.0.4, it breaks here and there. It already become tradition. Another debugging ritual and time-sacrifice perhaps can cure the backward-incompatibility-curse.

**Comment by stefantalpalaru** [comment]
We can't blame this on the new Nim version. Those tests were not running on Linux for this master branch commit from 5 days ago: https://travis-ci.org/status-im/nimbus/jobs/641426569#L14495

**Comment by jangko** [comment]
found the culprit, a typo made by me:

https://github.com/status-im/nimbus/blob/9047c6de2c2fcc8ece7d895b521d1dfcf2fe23c5/tests/test_blockchain_json.nim#L682

the 'C' of 'Chain' should be capitalized:

`jsonTest("newBlockChainTests", testFixture, skipNewBCTests)`

**Comment by stefantalpalaru** [comment]
But why did it work on Windows? Is string comparison case-insensitive there?

**Comment by stefantalpalaru** [comment]
Wait, that's a directory name and Windows directories are case-insensitive.

**Pull request merged**
