### PR TITLE
Fix block 81383 and block 81666 problem

### PR DESCRIPTION
**Pull request by jangko**
summary of this PR:
* allow us to sync until block 85858
* pass additional 29 GST

### CODE REVIEW

**Comment by jangko** [comment]
with this additional commits, we are able to reach block 196647, almost 200K

**Comment by jangko** [comment]
now we are at block 226522, over 226K

**Comment by zah** [comment]
This looks great, @jangko, kudos for the progress.
There is a strange RPC test failure though, I struggle to see how it could be related to the changes here, but can you please take a look? I'll merge everything once the CIs are green.

**Comment by jangko** [comment]
if we compile and run `test_rpc` alone, the crash not appear. it only appear if we compile it together with `all_tests.nim`.
Also, appveyor 32 bit not failed. don't know why.

**Pull request merged**
