### PR TITLE
Nim 1.0.4

### PR DESCRIPTION
**Pull request by stefantalpalaru**

### CODE REVIEW

**Comment by jangko** [comment]
I could not reproduce the failure using both nim 1.0.4 and nim devel branch.

**Comment by stefantalpalaru** [comment]
I restarted one of the AppVeyor jobs and it passed this time. What's weird about this spurious failure is that it happened at the same spot in both jobs, the first time.

Have you tried running that test in a loop until it fails?

**Comment by stefantalpalaru** [comment]
It also failed 7 days ago, in the same test, on both architectures, in one or two subtests (those are the forks?):

https://ci.appveyor.com/project/nimbus/nimbus/builds/29055190/job/nlxex8eulb4guocw#L11578

https://ci.appveyor.com/project/nimbus/nimbus/builds/29055190/job/9muxpekct4qj3ncg#L11592

**Comment by jangko** [comment]
> It also failed 7 days ago, in the same test, on both architectures, in one or two subtests (those are the forks?):

subtest no 7 #424 already fixed by #425. I can reproduce that one.
but this one seems like a mysterious hiccup, outdated cache maybe.

**Pull request merged**
