### PR TITLE
constantinople's implementation

### PR DESCRIPTION
**Pull request by jangko**
complete implementation + tests will come next

### CODE REVIEW

**Comment by jangko** [comment]
could someone restart appveyor?

**Comment by stefantalpalaru** [comment]
Restarted from https://ci.appveyor.com/project/nimbus/nimbus because there are no control buttons on https://ci.appveyor.com/project/jarradh/nimbus-aubsn/builds/24194580 - terrible UI design.

**Comment by jangko** [comment]
thank you

**Comment by stefantalpalaru** [comment]
We're leaving this as WIP while the rest is added?

**Comment by jangko** [comment]
no problem I think. I'm gonna implement the rest anyway.

**Comment by jangko** [comment]
this PR is ready for review. only 2 GST left. So far I've sync to block number 4.525.000 without any incident.

**Comment by stefantalpalaru** [comment]
Depends on https://github.com/status-im/nim-stint/pull/76, right?

**Comment by jangko** [comment]
> Depends on status-im/nim-stint#76, right?
that's right, current workaround also works and pass all arithmetic test albeit slower.

**Comment by stefantalpalaru** [comment]
Looks like you also need to bump std_shims.

**Pull request merged**
