### PR TITLE
ENode object and utility procedures.

### PR DESCRIPTION
**Pull request by cheatfate**
ENode handling procedures and tests.

### CODE REVIEW

**Comment by cheatfate** [comment]
@yglukhov actually everything from nim-eth-p2p will go to nimbus.

**Comment by yglukhov** [comment]
Why not just move eth-p2p to nimbus altogether now?

**Comment by zah** [comment]
@cheatfate, we haven't decided to move everything from `p2p` to Nimbus yet. The last plan was that we'll try to define some of the required dependencies as concepts (e.g. things like the state database) and we'll then supply concrete instances from the Nimbus code. This may turn out to be more trouble than it's worth it, but we should give it a shot.

Otherwise, the code looks good.

**Comment by zah** [comment]
The possibility to create projects such as https://github.com/holisticode/pss-chat-demo looks interesting and this would be the primary motivation about keeping such separation.

On the other hand, someone can just create a dependency on Nimbus and then import only specific modules.

**Comment by cheatfate** [comment]
Not right place for this PR

**Pull request closed without merging**
