### PR TITLE
add diffficulty test

### PR DESCRIPTION
**Pull request by jangko**

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
If "difficulty.nim" is only used in the test suite, shouldn't it be in the "tests/" directory?

**Comment by jangko** [comment]
It will be used by util/header.nim to construct a block header later, after we have implemented block chain test

**Comment by stefantalpalaru** [comment]
OK

**Comment by stefantalpalaru** [comment]
You saw the 32-bit failures, right?

**Comment by jangko** [comment]
it was status-im/nim-beacon-chain#353. it should be green after you merge them

**Comment by jangko** [comment]
but i'll will rebase and activates the test first

**Pull request merged**
