### PR TITLE
(WIP) Call fixes precompiles

### LINKED ISSUE #122: Implement all precompiled contracts
We need implementations and dispatching logic for the following precompiles

Introduced in Homestead:
- [ ] 0x1 ecrecover
- [ ] 0x2 sha256
- [ ] 0x3 ripemd160
- [ ] 0x4 identity

Introduced in Byzantium:
- [ ] 0x5 modexp
- [ ] 0x6 ecadd
- [ ] 0x7 ecmul
- [ ] 0x8 ecpairing
 
Reference implementations:
https://github.com/ethereum/py-evm/tree/master/eth/precompiles

### PR DESCRIPTION
**Pull request by mratsim**
Fix #122, required by #121 

I'm opening it the PR to start discussion implementation (or things not implemented) and tests.

-----

A change in `eth_trie` file structure broke the CI: https://travis-ci.org/status-im/nimbus/jobs/437522149#L1050

### CODE REVIEW

**Comment by tersec** [comment]
When the `GeneralStateTests.md` changes show up, it would also be good to add the newly passing tests to `test_generalstate_failing.nim` for to prevent regressions.

**Comment by coffeepots** [comment]
@tersec Calling for review for this work to be merged before continuing on the state tests.
In response to your query, I'm not sure why the stPreCompiledContracts2 don't pass yet but it's worth noting there is currently an issue in the `modexp` precompile that needs fixing. However this branch still pushes forward more passing tests so I believe it's worth doing these fixes in another PR to prevent more merge conflicts going forward.

**Comment by mratsim** [comment]
Regarding `modExp` are some tests passing and other failings or are all failing?

**Comment by coffeepots** [comment]
@mratsim ModExp currently fails in two ways:

**1. Consuming Data**

Fails assertion when consuming data here: https://github.com/status-im/nimbus/blob/0366dd47d94c07e7d32606343adfda6043b7a59d/nimbus/vm/precompiles.nim#L117

```base = rawMsg.rangeToPaddedUint256(96, start_exp - 1)``` fails an assertion check in `io.nim` because some tests use a `base_len` that is >32.

**2. Results**

The remaining tests that don't have the above error are `eip_example1` and `eip_example2`
`eip_example1`:
Output  : 0000000000000000000000000000000000000000000000000000000000000000
Expected: 0000000000000000000000000000000000000000000000000000000000000001
`eip_example2`: Passes, but is expecting zero output anyway.

**Comment by tersec** [comment]
> @tersec Calling for review for this work to be merged before continuing on the state tests.
> In response to your query, I'm not sure why the stPreCompiledContracts2 don't pass yet but it's worth noting there is currently an issue in the `modexp` precompile that needs fixing. However this branch still pushes forward more passing tests so I believe it's worth doing these fixes in another PR to prevent more merge conflicts going forward.

I agree.

**Pull request merged**
